force-app/main/default/objects/Crm_Service__c/Crm_Service__c.object-meta.xml
<CustomObject>
    <label>Crm Service</label>
    <nameField>
        <label>Crm Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crm Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Crm_Service__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Crm_Service_Usage__c/fields/Crm_Service__c.field-meta.xml
<CustomField>
    <fullName>Crm_Service__c</fullName>
    <label>Crm Service</label>
    <referenceTo>Crm_Service__c</referenceTo>
    <relationshipLabel>Crm Service Usages</relationshipLabel>
    <relationshipName>Crm_Service_Usages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Crm_Service_Usage__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Crm_Service_Usage__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Crm_Service_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Crm_Service_Usage__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GatekeeperHandler.cls
public without sharing class GatekeeperHandler implements IGatekeeperHandler {
    private IGatekeeperValidator validator = new GatekeeperValidator();
    private ICrmServiceUsageService usageService = new CrmServiceUsageService();

    private GatekeeperUtil.GatekeeperRequest getGatekeeperReq(RestRequest req) {
        GatekeeperUtil.GatekeeperRequest gkReq = null;
        try {
            gkReq = GatekeeperUtil.getGateKeeperRequestByRestRequest(req);    
        } catch (Exception e) {
            System.debug('GatekeeperHandler.getGatekeeperReq => '+ e.getMessage());
            //throw new GatekeeperUtil.GatekeeperException(e.getMessage());
            gkReq = null;
        }
        return gkReq;
    }

    private Crm_Service_Usage__c createUsageRecord(RestRequest req, GatekeeperUtil.GatekeeperRequest gkReq) {
        Crm_Service_Usage__c result = null;
        try {
            
            Map<String,Object> props = new Map<String,Object> {
                'Status__c' => 'New',
                'Response__c' => '',
                'Requester__c' => UserInfo.getUserId(),
                'Request__c' => JSON.serialize(req),
                'Crm_Service__c' => ((gkReq != null && !String.isBlank(gkReq.serviceName)) ? gkReq.serviceName: ''),
                'Comment__c' => ''
            };
            result = usageService.createCrmServiceUsage(props);
        }
        catch(Exception e) {
            throw new GatekeeperUtil.GatekeeperException(e.getMessage());
        }
        return result;
    }

    public GatekeeperUtil.GatekeeperResponse handle(RestRequest req) {
        GatekeeperUtil.GatekeeperResponse response = null;
        try 
        {
            GatekeeperUtil.GatekeeperRequest gkReq = getGatekeeperReq(req);
            Crm_Service_Usage__c usageRecord = createUsageRecord(req, gkReq);
            response = validator.validateGatekeeperRequest(req);
        }
        catch (Exception e) {
            throw new GatekeeperUtil.GatekeeperException(e.getMessage());    
        }
        return response;
    }
}